{"name": "test_div_1[1-0]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <allurepython.testpytest.TestCalc object at 0x000001BC2AC0BCC0>\na = 1, b = 0\n\n    @pytest.mark.parametrize((\"a\",\"b\"),yaml.safe_load(open(\"./data.yaml\")))\n    def test_div_1(self,a,b):\n        try:\n            self.demo1 = demo1()\n>           result = self.demo1.div(a,b)\n\ntestpytest.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allurepython.demo1.demo1 object at 0x000001BC2AC1B6A0>, a = 1\nb = 0\n\n    def div(self, a, b):\n>       return a / b\nE       ZeroDivisionError: division by zero\n\ndemo1.py:6: ZeroDivisionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <allurepython.testpytest.TestCalc object at 0x000001BC2AC0BCC0>\na = 1, b = 0\n\n    @pytest.mark.parametrize((\"a\",\"b\"),yaml.safe_load(open(\"./data.yaml\")))\n    def test_div_1(self,a,b):\n        try:\n            self.demo1 = demo1()\n            result = self.demo1.div(a,b)\n            print(result)\n            assert (a/b) == result\n        except Exception as e:\n>           assert False\nE           AssertionError\n\ntestpytest.py:21: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "0"}], "start": 1594614491272, "stop": 1594614491272, "uuid": "b3c63858-e5b8-41d0-9e07-5eab36294e33", "historyId": "bf9a3f01d3536b6e028a8861c381b166", "testCaseId": "a0aa7ebe85b3ed3fa171ee3a7a957ed8", "fullName": "testpytest.TestCalc#test_div_1", "labels": [{"name": "suite", "value": "testpytest"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LAPTOP-LN6AGCK9"}, {"name": "thread", "value": "44932-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testpytest"}]}